;Deklarationen***********************************************************
;Muessen an die vorhandene Anschlussbelegung angepasst werden!

#define	LCD_E		PORTA,1
#define	LCD_D4		PORTB,2
#define	LCD_D5		PORTB,3
#define	LCD_D6		PORTB,4
#define	LCD_D7		PORTB,5
#define	LCD_RS		PORTB,6
#define	LCD_RW		PORTB,7

#define	ADC_CS		PORTA,0
#define	ADC_D		PORTB,2
#define	ADC_CLK		PORTB,3

#define SW_E		PORTA,2
#define SW_0		PORTB,2
#define SW_1		PORTB,3
#define SW_2		PORTB,4
#define SW_3		PORTB,5

#define RxD		PORTB,0
#define TxD		PORTB,1

#define SPK		PORTA,3

#define	KB_CLK		PORTA,4
#define	KB_D		PORTB,6